apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-services.yaml
  - cloud-privilege-broker.yaml
  - zuul.yaml
  - platform.yaml
  - maw.yaml

commonLabels:
  argo.beyondtrust.com/deployment-environment: production