apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/cluster-services.yaml
  - resources/cloud-privilege-broker.yaml
  - resources/zuul.yaml
  - resources/platform.yaml
  - resources/maw.yaml

commonLabels:
  argo.beyondtrust.com/deployment-environment: production