apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-services
  namespace: argocd
spec:
  description: "Services that keep production running a-oh-kay"
  destinations:
  - namespace: gatekeeper-system
    server: https://DC562B007375BD6788916029314E1C00.sk1.us-east-1.eks.amazonaws.com
  - namespace: datadog-system
    server: https://DC562B007375BD6788916029314E1C00.sk1.us-east-1.eks.amazonaws.com

  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-cluster-services-prod
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: production/cluster-services/bootstrap
    repoURL: git@github.com:BeyondTrust/hatchery.git
    targetRevision: master